# cleaning.R
# Delete either the last digest or all digests.
# Set MODE to "last" or "all", then source the script.

MODE <- "last"   # "last"  →  remove only the most recent digest
                 # "all"   →  remove everything generated by website.R

library(here)
library(yaml)

`%||%` <- function(a, b) if (!is.null(a)) a else b

archives_dir <- here("archives")
data_path    <- here("_data", "digests.yml")

# ---- helpers ---------------------------------------------------------------

read_registry <- function(path) {
  if (!file.exists(path)) return(list())
  yaml::read_yaml(path)
}

write_registry <- function(reg, path) {
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  yaml::write_yaml(reg, path)
}

remove_file <- function(f) {
  if (file.exists(f)) { file.remove(f); cat("Deleted:", f, "\n") }
  else cat("Not found (skipped):", f, "\n")
}

remove_dir <- function(d) {
  if (dir.exists(d)) { unlink(d, recursive = TRUE); cat("Deleted dir:", d, "\n") }
  else cat("Not found (skipped):", d, "\n")
}

# ---- digest files ----------------------------------------------------------

all_digest_files <- list.files(archives_dir, pattern = "^digest-[0-9].*\\.md$",
                               full.names = TRUE)

if (length(all_digest_files) == 0) {
  cat("No digest files found in", archives_dir, "\n")
  stop("Nothing to clean.")
}

# ============================================================
if (MODE == "last") {
# ============================================================

  # Identify the most recent digest file (alphabetical = chronological for YYYY-WW).
  last_file <- sort(all_digest_files)[length(all_digest_files)]
  last_slug <- sub("^.*digest-(.+)\\.md$", "\\1", last_file)

  cat("--- Removing last digest:", basename(last_file), "---\n")

  # 1. Delete digest markdown page.
  remove_file(last_file)

  # 2. Remove from registry and rewrite.
  reg <- read_registry(data_path)
  if (length(reg) > 0) {
    # Find entry whose slug or url matches last_slug.
    keep <- Filter(function(e) {
      slug_match <- identical(as.character(e$slug %||% ""), last_slug)
      url_match  <- grepl(paste0("digest-", last_slug, "/"),
                          as.character(e$url %||% ""), fixed = TRUE)
      !slug_match && !url_match
    }, reg)
    write_registry(keep, data_path)
    cat("Registry updated:", length(reg) - length(keep), "entry removed.\n")
  }

  # 3. Remove matching feeds RData snapshot.
  # Slug is either YYYY-WW (new) or a plain number (legacy).
  is_new_slug <- grepl("^\\d{4}-\\d+$", last_slug)
  if (is_new_slug) {
    year_part <- sub("-\\d+$",   "", last_slug)   # e.g. "2026"
    week_part <- sub("^\\d{4}-", "", last_slug)   # e.g. "22"
    feed_file <- file.path(archives_dir, "feeds", year_part,
                           paste0("feed_", week_part, ".RData"))
    remove_file(feed_file)
  } else {
    # Legacy slug (plain number): scan all year folders for any matching snapshot.
    feeds_root <- file.path(archives_dir, "feeds")
    if (dir.exists(feeds_root)) {
      rdata_files <- list.files(feeds_root, pattern = "\\.RData$",
                                recursive = TRUE, full.names = TRUE)
      if (length(rdata_files) > 0) {
        cat("Legacy slug — cannot match feed snapshot automatically.\n")
        cat("Feed snapshots present (delete manually if needed):\n")
        for (f in rdata_files) cat(" ", f, "\n")
      }
    }
  }

  # 4. Delete regenerated pages (will be rebuilt correctly on next run).
  remove_file(here("index.md"))
  remove_file(file.path(archives_dir, "index.md"))
  remove_file(here("robots.txt"))

  cat("Done. Re-run website.R to regenerate the site.\n")

# ============================================================
} else if (MODE == "all") {
# ============================================================

  cat("--- Removing ALL digests ---\n")

  # 1. Delete all digest markdown pages.
  for (f in all_digest_files) remove_file(f)

  # 2. Wipe the registry.
  remove_file(data_path)

  # 3. Remove entire feeds snapshot folder.
  remove_dir(file.path(archives_dir, "feeds"))

  # 4. Delete all regenerated site pages.
  remove_file(here("index.md"))
  remove_file(file.path(archives_dir, "index.md"))
  remove_file(here("robots.txt"))

  # 5. Optionally clear LLM caches (uncomment to also reset cached tags/titles).
  # remove_file(file.path(archives_dir, "llm_tags_cache.rds"))
  # remove_file(file.path(archives_dir, "llm_title_cache.rds"))
  # remove_file(file.path(archives_dir, "title_cache.rds"))

  cat("Done. Re-run website.R to regenerate the site from scratch.\n")

# ============================================================
} else {
  stop('MODE must be "last" or "all".')
}
